// auto generated by configure
#ifndef SRS_AUTO_HEADER_HPP
#define SRS_AUTO_HEADER_HPP

#define SRS_AUTO_BUILD_TS "1552994747"
#define SRS_AUTO_BUILD_DATE "2019-03-19 19:25:47"
#define SRS_AUTO_UNAME "Darwin bilibil-test-5.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64"
#define SRS_AUTO_USER_CONFIGURE "--x86-x64  --export-librtmp-project=../../srs-librtmp3.0 --without-ssl"
#define SRS_AUTO_CONFIGURE "--prefix=/usr/local/srs --with-hls --without-hds --with-dvr --without-nginx --without-ssl --without-ffmpeg --without-transcode --without-ingest --without-stat --without-http-callback --with-http-server --without-stream-caster --without-kafka --with-http-api --with-librtmp --with-research --without-utest --without-gperf --without-gmc --without-gmd --without-gmp --without-gcp --without-gprof --without-arm-ubuntu12 --without-mips-ubuntu12 --log-trace"

#define SRS_X86_X64
#define SRS_X86_X64_BOOL true
#define SRS_EXPORT_LIBRTMP

#undef SRS_AUTO_EMBEDED_TOOL_CHAIN
#define SRS_AUTO_EMBEDED_TOOL_CHAIN_BOOL false

#undef SRS_AUTO_KAFKA
#define SRS_AUTO_KAFKA_BOOL false
#undef SRS_AUTO_NGINX
#define SRS_AUTO_NGINX_BOOL false
#undef SRS_AUTO_HDS
#define SRS_AUTO_HDS_BOOL false
#undef SRS_AUTO_MEM_WATCH
#define SRS_AUTO_MEM_WATCH_BOOL false
#undef SRS_AUTO_FFMPEG_TOOL
#define SRS_AUTO_FFMPEG_TOOL_BOOL false
#define SRS_AUTO_FFMPEG_STUB
#define SRS_AUTO_FFMPEG_STUB_BOOL true
#undef SRS_AUTO_GPERF
#define SRS_AUTO_GPERF_BOOL false
#undef SRS_AUTO_GPERF_MC
#define SRS_AUTO_GPERF_MC_BOOL false
#undef SRS_AUTO_GPERF_MD
#define SRS_AUTO_GPERF_MD_BOOL false
#undef SRS_AUTO_GPERF_MP
#define SRS_AUTO_GPERF_MP_BOOL false
#undef SRS_AUTO_GPERF_CP
#define SRS_AUTO_GPERF_CP_BOOL false
#undef SRS_AUTO_EMBEDED_CPU
#define SRS_AUTO_EMBEDED_CPU_BOOL false
#undef SRS_AUTO_ARM_UBUNTU12
#define SRS_AUTO_ARM_UBUNTU12_BOOL false
#undef SRS_AUTO_MIPS_UBUNTU12
#define SRS_AUTO_MIPS_UBUNTU12_BOOL false

#undef SRS_AUTO_VERBOSE
#define SRS_AUTO_VERBOSE_BOOL false
#undef SRS_AUTO_INFO
#define SRS_AUTO_INFO_BOOL false
#define SRS_AUTO_TRACE
#define SRS_AUTO_TRACE_BOOL true

#define SRS_AUTO_PREFIX "/usr/local/srs"

#define SRS_AUTO_CONSTRIBUTORS "\
winlin<winlin@vip.126.com> \
wenjie.zhao<740936897@qq.com> \
xiangcheng.liu<liuxc0116@foxmail.com> \
naijia.liu<youngcow@youngcow.net> \
alcoholyi<alcoholyi@qq.com> \
byteman<wangchen2011@gmail.com> \
chad.wang<chad.wang.cn@gmail.com> \
suhetao<suhetao@gmail.com> \
Johnny<fengjihu@163.com> \
karthikeyan<keyanmca@gmail.com> \
StevenLiu<lq@chinaffmpeg.org> \
zhengfl<zhengfl_1989@126.com> \
tufang14<breadbean1449@gmail.com> \
allspace<allspace@gmail.com> \
niesongsong<nie950@gmail.com> \
rudeb0t<nimrod@themanxgroup.tw> \
CallMeNP<np.liamg@gmail.com> \
synote<synote@qq.com> \
lovecat<littlefawn@163.com> \
panda1986<542638787@qq.com> \
YueHonghui<hongf.yue@hotmail.com> \
ThomasDreibholz<dreibh@simula.no> \
JuntaoLiu<juntliu@gmail.com> \
RocFang<fangpeng1986@gmail.com> \
MakarovYaroslav<yaroslav.makarov.97@mail.ru> \
MirkoVelic<mvelic@inoxx.net> \
HuiZhang(huzhang2)<huzhang2@cisco.com> \
OtterWa<simpleotter23@gmail.com> \
walkermi<172192667@qq.com> \
haofz<fuzhuang.hao@vhall.com> \
ME_Kun_Han<hanvskun@hotmail.com> \
ljx0305<ljx0305@gmail.com> \
cenxinwei<censhanhe@163.com> \
StarBrilliant<m13253@hotmail.com> \
xubin<xubin@chnvideo.com> \
intliang<yintiliang@gmail.com> \
flowerwrong<sysuyangkang@gmail.com> \
"

#endif

